### ISSUE TITLE
Could not resolve all artifacts for configuration ':geocoder:classpath'. ANDROID / Flutter

### ISSUE THREAD

**Issue by Peter-717** [aloisdeniel/flutter_geocoder#11]
Though the plugin works like a charm on iOS (Thanks!!), I am getting the following error on Android:
my config:
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'   // new
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

Yaml dependencies:
  font_awesome_flutter: ^8.2.0
  carousel_pro: ^0.0.13
  date_format: ^1.0.5
  dots_indicator: ^0.0.4

  cloud_firestore: ^0.8.2+3
  google_sign_in: ^3.2.4
  flutter_facebook_login: ^1.1.1
  firebase_auth: ^0.6.6
  firebase_storage: ^1.0.4
  connectivity: ^0.3.2
  intl: ^0.15.7
  geolocator: ^2.1.1
  geocoder: ^0.1.2
  image_picker: ^0.4.10
  flutter_image_compress: ^0.2.2

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "xxxxx/android/gradlew" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :geocoder

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':geocoder'.
> Could not resolve all artifacts for configuration ':geocoder:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
       - https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
       - https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
     Required by:
         project :geocoder

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
  Command: /xxxxx/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by aschiavon91** [comment]
i fixed it by upgrading buildToolsVersion in `flutter_geocoder/android/build.gradle` to `'26.0.3'`
open ur project in android studio, change files view to project, u will see the flutter_geocoder folder.
In anyway, i opened the pr #10 and order to fixed it

**Comment by Peter-717** [comment]
Thanks ! I just did as per your instruction, but I am still getting the same error.

**Comment by Peter-717** [comment]
In the same file, I also upgraded the dependencies to ‘com.android.tools.build:gradle:3.2.1’.
Now everything works fine.
Thanks again for your prompt support.
Much appreciated!

**Comment by Pradeepa651** [comment]
* What went wrong:
A problem occurred configuring project ':firebase_auth'.
> Could not resolve all files for configuration ':firebase_auth:classpath'.
